name: Manual Inputs
on: 
  workflow_dispatch:

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT"
            echo ${{ github.head_ref }}
            echo "##[set-output name=commits_ur;]$(echo ${{ github.event.repository.comments_url }})"
        id: commit_urls

      - run: curl -o out.json ${{ steps.commit_urls.outputs.commits_url }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: commits
          path: out.json
