name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      url_api:
           description: Add Test URL
           required: true

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          TEST_URL: ${{ github.event.inputs.url_api }}
    
      - run: echo $TEST_URL
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: echo "$GITHUB_CONTEXT"
      - run: curl -o out.json ${{ github.event.pull_request.commits_url }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: commits
          path: out.json
